site_name: Sakila DB for PostgreSQL
site_author: STÜBER SYSTEMS GmbH
site_description: Documentation of the Sakila Sample Database Schema for PostgreSQL

copyright:
  '&copy; 2025 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/en/imprint.php">Imprint</a> : <a href="https://legal.stueber.de/en/privacy.php">Privacy</a>'

theme:
  name: material
  language: en
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  static_templates:
    - 404.html
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: false

extra:
  version:
    provider: mike

extra_css:
  - assets/css/custom.css

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg